version: "3"
services:
  postgres:
    build:
      context: ./src/database/
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    networks:
      - local

  api:
    build: .
    image: api-jwt-auth
    volumes:
      - .:/app
    environment:
      - DATABASE_HOST=postgres
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - local

networks:
  local:
    driver: bridge
